name: Test Publish

on:
  pull_request:
    branches:
      - main

jobs:
  publish:
    name: Test Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: '**/package-lock.json'

      - name: Generate legacy schemas
        run: |
          mvn package exec:java -Ddhis2.api.version=2.39.1 -Dschemas.output.dir=schemas/v2.39.1 -Ddocs.output.dir=docusaurus/docs/v2.39.1
          mvn package exec:java -Ddhis2.api.version=jitpack~2.38.1-SNAPSHOT -Dlabel=2.38.1 -Dschemas.output.dir=schemas/v2.38.1
          mvn package exec:java -Ddhis2.api.version=2.37.7 -Dschemas.output.dir=schemas/v2.37.7
          mvn package exec:java  -P '!post-v2.37.5' -Ddhis2.api.version=2.36.11 -Dschemas.output.dir=schemas/v2.36.11
          mvn package exec:java  -P '!post-v2.37.5' -Ddhis2.api.version=2.35.13 -Dschemas.output.dir=schemas/v2.35.13

      - name: Generate DHIS2 40.0 schemas
        uses: mikefarah/yq@v4
        with:
          cmd: |
            mkdir -p schemas/v40.0 && cd schemas/v40.0
            yq -p=json -o=json '.components.schemas.* | (.. | select(key == "$ref")) |= sub(".*/(.*)", "${1}.json")' ../../openapi/v40.0/openapi.json -s 'key'

      - name: Generate DHIS2 40.2.2 schemas
        uses: mikefarah/yq@v4
        with:
          cmd: |
            mkdir -p schemas/v40.2.2 && cd schemas/v40.2.2
            yq -p=json -o=json '.components.schemas.* | (.. | select(key == "$ref")) |= sub(".*/(.*)", "${1}.json")' ../../openapi/v40.2.2/openapi.json -s 'key'        

      - name: Install dependencies
        run: yarn --cwd docusaurus install --frozen-lockfile
      - name: Build website
        run: NODE_OPTIONS=--max_old_space_size=10000 yarn --cwd docusaurus build
