name: Test Publish

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Test Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: '**/package-lock.json'

      - name: Generate schemas
        run: |
          mvn package exec:java -Ddhis2.api.version=jitpack~2.38.1-SNAPSHOT -Dlabel=v2.38.1 -Dschemas.output.dir=schemas/v2.38.1 -Ddocs.output.dir=docusaurus/docs/v2.38.1
          mvn package exec:java -Ddhis2.api.version=2.37.7 -Dschemas.output.dir=schemas/v2.37.7 -Ddocs.output.dir=docusaurus/docs/v2.37.7
          mvn package exec:java  -P '!post-v2.37.5' -Ddhis2.api.version=2.36.11 -Dschemas.output.dir=schemas/v2.36.11 -Ddocs.output.dir=docusaurus/docs/v2.36.11

      - name: Install dependencies
        run: yarn --cwd docusaurus install --frozen-lockfile
      - name: Build website
        run: NODE_OPTIONS=--max_old_space_size=10000 yarn --cwd docusaurus build